### ISSUE TITLE
Could you please share the retrained model?

### ISSUE THREAD

**Issue by Shuailong** [pchase8818/dynamic-memory-networks#3]
```
Loading babi data
{u'hallway': 1, u'bathroom': 2, u'garden': 4, u'office': 5, u'bedroom': 0, u'kitchen': 3}
6
Tensor("concat:0", shape=(20000, 80), dtype=float32)
Tensor("Placeholder_2:0", shape=(7000,), dtype=int32)
Tensor("Gather:0", shape=(7000, 80), dtype=float32)
Tensor("Reshape:0", shape=(70, 100, 80), dtype=float32)
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app import app
  File "/home/lsl/DMN-Vis/python/app/__init__.py", line 4, in <module>
    from app import dmn_demo
  File "/home/lsl/DMN-Vis/python/app/dmn_demo.py", line 80, in <module>
    saver.restore(session, PATH_TO_MODEL)
  File "/home/lsl/miniconda3/envs/dmn-vis/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1088, in restore
    raise ValueError("Restore called with invalid save path %s" % save_path)
ValueError: Restore called with invalid save path /Users/patrickchase/Documents/CS224D/finalProject/dynamic-memory-networks/data/weights/dmn_lr_0.001_r_0.001_hs_80_e_150_d_0.9_t_2_bs_100.weight
```

Could you please share the pretrained model?

**Comment by patrickachase** [comment]
Hi @Shuailong,

Unfortunately models are too big to push to github, but if you train it with those parameters on the larger babi dataset though you should get the same results.
